package com.wealth.fly.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class KLine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.id
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.currency_id
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private Integer currencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.data_time
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private Long dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.open
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private BigDecimal open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.close
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private BigDecimal close;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.high
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private BigDecimal high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.low
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private BigDecimal low;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.volume
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private Long volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.currency_volume
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private BigDecimal currencyVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.granularity
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private String granularity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kline.create_time
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.id
     *
     * @return the value of kline.id
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.id
     *
     * @param id the value for kline.id
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.currency_id
     *
     * @return the value of kline.currency_id
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public Integer getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.currency_id
     *
     * @param currencyId the value for kline.currency_id
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.data_time
     *
     * @return the value of kline.data_time
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public Long getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.data_time
     *
     * @param dataTime the value for kline.data_time
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setDataTime(Long dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.open
     *
     * @return the value of kline.open
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public BigDecimal getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.open
     *
     * @param open the value for kline.open
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.close
     *
     * @return the value of kline.close
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public BigDecimal getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.close
     *
     * @param close the value for kline.close
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setClose(BigDecimal close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.high
     *
     * @return the value of kline.high
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.high
     *
     * @param high the value for kline.high
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.low
     *
     * @return the value of kline.low
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public BigDecimal getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.low
     *
     * @param low the value for kline.low
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.volume
     *
     * @return the value of kline.volume
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.volume
     *
     * @param volume the value for kline.volume
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.currency_volume
     *
     * @return the value of kline.currency_volume
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public BigDecimal getCurrencyVolume() {
        return currencyVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.currency_volume
     *
     * @param currencyVolume the value for kline.currency_volume
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setCurrencyVolume(BigDecimal currencyVolume) {
        this.currencyVolume = currencyVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.granularity
     *
     * @return the value of kline.granularity
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public String getGranularity() {
        return granularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.granularity
     *
     * @param granularity the value for kline.granularity
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setGranularity(String granularity) {
        this.granularity = granularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kline.create_time
     *
     * @return the value of kline.create_time
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kline.create_time
     *
     * @param createTime the value for kline.create_time
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}