package com.wealth.fly.core.dao;


import com.wealth.fly.core.entity.KLine;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface KLineDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int insert(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int insertSelective(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    KLine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int updateByPrimaryKeySelective(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int updateByPrimaryKey(KLine record);

    List<KLine> getLastKLineByGranularity(@Param("granularity") String dataGranularity, @Param("limit") int limit);

    List<KLine> getLastKLineGTDataTime(@Param("granularity") String dataGranularity,@Param("dataTime") Long dataTime , @Param("limit") int limit);
}