package com.wealth.fly.core.dao;

import com.wealth.fly.core.entity.KLine;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KLineDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Sun Dec 13 21:54:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Sun Dec 13 21:54:14 CST 2020
     */
    int insert(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Sun Dec 13 21:54:14 CST 2020
     */
    int insertSelective(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Sun Dec 13 21:54:14 CST 2020
     */
    KLine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Sun Dec 13 21:54:14 CST 2020
     */
    int updateByPrimaryKeySelective(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Sun Dec 13 21:54:14 CST 2020
     */
    int updateByPrimaryKey(KLine record);

    List<KLine> getLastKLineByGranularity(@Param("granularity") String dataGranularity, @Param("limit") int limit);

    List<KLine> getLastKLineGTDataTime(@Param("granularity") String dataGranularity, @Param("dataTime") Long dataTime, @Param("limit") int limit);

    List<KLine> getLastKLineLEDataTime(@Param("granularity") String dataGranularity, @Param("dataTime") Long dataTime, @Param("limit") int limit);

    List<KLine> getLastKLineByDataTime(@Param("granularity") String dataGranularity, @Param("startTime") Long startTime,@Param("endTime") Long endTime, @Param("limit") int limit);

    KLine getKlineByDataTime(@Param("granularity") String dataGranularity, @Param("dataTime") Long dataTime);

    List<KLine> getLastKLineByDataTimeRange(@Param("granularity") String dataGranularity, @Param("dataTimeBegin") Long dataTimeBegin, @Param("dataTimeEnd") Long dataTimeEnd);

}