package com.wealth.fly.core.dao;

import com.wealth.fly.core.constants.DataGranularity;
import com.wealth.fly.core.entity.KLine;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface KLineDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int insert(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int insertSelective(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    KLine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int updateByPrimaryKeySelective(KLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kline
     *
     * @mbg.generated Tue May 12 22:36:03 CST 2020
     */
    int updateByPrimaryKey(KLine record);

    KLine getLastKLineByGranularity(@Param("granularity") String dataGranularity);
}